[package]
name = "intaglio"
version = "1.0.1"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "UTF-8 string and bytestring interner and symbol table"
repository = "https://github.com/artichoke/intaglio"
readme = "README.md"
license = "MIT"
keywords = ["bytestring", "intern", "interner", "symbol", "utf8"]
categories = ["caching", "data-structures"]
include = [
  "src/**/*.rs",
  "benches/**/*.rs",
  "tests/**/*.rs",
  "LICENSE",
  "README.md"
]

[[bench]]
name = "benchmarks"
harness = false

[features]
# All features are enabled by default.
default = ["bytes"]
# `bytes` feature enables an additional symbol table implementation for
# interning bytestrings (`Vec<u8>` and `&'static [u8]`). When this feature is
# enabled, Intaglio will depend on [`bstr`].
bytes = ["bstr"]

[dependencies]
# The dependency on bstr is not strictly necessary, but `intaglio` uses the
# `fmt::Debug` impl on `BStr` to provide readable debug representations of the
# bytestring interner variant.
#
# If keys are conventionally UTF-8, their UTF-8 portions will be rendered as
# characters. The UTF-8 invalid parts will be shown as e.g. \xFF escape codes
# which is also an improvement of how `std` implements `fmt::Debug` for byte
# slices.
bstr = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
# Benchmarking support on stable Rust.
criterion = "0.3"
# Property testing for interner getters and setters.
quickcheck = { version = "0.9", default-features = false }
quickcheck_macros = "0.9"
# Check that crate versions are properly updated in documentation and code when
# bumping the version.
version-sync = "0.9"

[target.'cfg(target_os = "linux")'.dev-dependencies]
# `libc::getrusage` is used to check for memory leaks on Linux in CI.
libc = "0.2"
